spring:
  application:
    name: tlias-web-management
    #数据库连接信息
  datasource:
    url: jdbc:mysql://192.168.100.128:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
#mybatis配置信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开始驼峰命名映射开关
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/zcf/mapper/*.xml
pagehelper:
  reasonable: true
  helper-dialect: mysql

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

servlet:
  multipart:
    #最大单个文件大小
    max-file-size: 10MB
    #最大请求大小(包括所有文件和表单数据)
    max-request-size: 100MB

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-ai-zcf
    region: cn-beijing